functionsDirectory = "C:\\Users\\Sammy\\Downloads\\effective-communication-registration-form\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\Sammy\\Downloads\\effective-communication-registration-form"
publishOrigin = "default"
functions = "C:\\Users\\Sammy\\Downloads\\effective-communication-registration-form\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]